version: '3.2'
services:
  app:
    build: ./app
    volumes:
      - sockets:/usr/src/app/tmp/sockets
      - ./app/volume/database:/usr/src/app/database
      - ./app/volume/log:/usr/src/app/log
      - ./app/volume/uploads:/usr/src/app/public/uploads
  web:
    build: ./web
    ports:
      - "80:80"
    volumes:
      - sockets:/var/tmp/sockets
      - ./web/volume/log:/var/log/nginx
volumes:
  sockets:
